name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      manualVersion:
        description: "Version of package to publish"
        required: true

jobs:
  check-for-api-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true

      - name: Commit submodule
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api-src
          git commit -m "Updating bungie-net/api submodule"

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302

      - name: Yarn install
        run: yarn --cwd ./generator install

      - name: Generate classes
        run: yarn --cwd ./generator start

      - name: Check if there were changes
        id: code-changed
        run: echo ::set-output name=dirty::"$(git status --porcelain)"

      - name: Get Bungie API version
        id: api-version
        run: echo "::set-output name=value::$(cat bungie-api-version)"

      - name: Update version in .csproj
        run: sed -i "s/<Version>.*<\/Version>/<Version>${{ github.event.inputs.manualVersion }}<\/Version>/" GhostSharp.csproj

      - name: Build and publish to NuGet
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: GhostSharp.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_COMMIT: false

      - name: Commit everything
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "Manually published Bungie API spec version ${{ steps.api-version.outputs.value }}, GhostSharper version ${{ github.event.inputs.manualVersion }}"
          git tag v${{ github.event.inputs.manualVersion }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
